Msdeo 279 defect view symptom doesnt comply with mock
MSE-2019-2021/support_care pull request #75
Opened 2020-12-22 10:40 UTC by aamarques

2020-12-22 15:38 UTC, DanielFran requested changes

2020-12-22 15:38 UTC, DanielFran commented on src/main/webapp/app/entities/symptom/symptom-detail.component.html
> +<!--    <span class="col-8">-->
Delete commented code

2020-12-22 15:38 UTC, DanielFran commented on src/main/webapp/app/entities/symptom/symptom-detail.component.html
> +<!--    </span>-->
Delete commented code

2020-12-22 16:37 UTC, sfdsilva approved these changes

2020-12-23 10:49 UTC, xalves commented
QA Aproved

2020-12-23 15:39 UTC, merged