MSEDO-275 - Edit Active Substances
MSE-2019-2021/support_care pull request #82
Opened 2021-01-04 22:18 UTC by andrenns

2021-01-05 10:33 UTC, aamarques requested changes
Is it a good approach to verify/remove all variables that will be never used as showed on annotatios

2021-01-05 10:33 UTC, aamarques commented on src/main/webapp/app/entities/active-substance/list/active-substance.component.html
> +    <!--<button *customHasAnyAuthority="'ROLE_USER'" id="jh-create-entity" data-cy="entityCreateButton" class="btn btn-primary jh-create-entity button-create" [routerLink]="['/active-substance/new']"
Remove Comments from code before submitting it to Master

2021-01-05 10:33 UTC, aamarques commented on src/main/webapp/app/entities/active-substance/list/active-substance.component.html
> +    </button>-->
Remove Comments from code before submitting it to Master

2021-01-05 10:33 UTC, aamarques commented on src/test/javascript/cypress/integration/entity/active-substance.spec.ts
> +  /*it('should load create ActiveSubstance page', () => {
Remove Comments from code before submitting it to Master

2021-01-05 10:33 UTC, aamarques commented on src/test/javascript/cypress/integration/entity/active-substance.spec.ts
> +  });*/
Remove Comments from code before submitting it to Master

2021-01-05 22:21 UTC, andrenns commented
> Is it a good approach to verify/remove all variables that will be never used as showed on annotatios

The tests are commented because when QA decides they will be corrected and used

And the button is commented because PO was not sure if that button should be deleted or not, so if in a sprint or two she decides we should use it is there, otherwise we will remove it

2021-01-06 23:04 UTC, merged

2021-01-06 23:04 UTC, aamarques commented
Merged to master