fix: BE changes to accomodate files changes on edition WIP (MSEDO-319)
MSE-2019-2021/support_care pull request #84
Opened 2021-01-08 00:36 UTC by sfdsilva

MSEDO-319

2021-01-08 00:58 UTC, DanielFran requested changes

2021-01-08 00:58 UTC, DanielFran commented on src/main/java/uc/dei/mse/supportivecare/service/OutcomeService.java
> +        Set<DocumentDTO> outcomeDocumentsDTO = outcomeDTO.getDocuments();
remove

2021-01-08 00:58 UTC, DanielFran commented on src/main/java/uc/dei/mse/supportivecare/service/OutcomeService.java
> +        outcomeDocumentsDTO
Substitute outcomeDocumentsDTO by outcomeDTO.getDocuments()

2021-01-08 00:58 UTC, DanielFran commented on src/main/java/uc/dei/mse/supportivecare/service/dto/OutcomeDTO.java
> +    public void addToDocuments(Set<DocumentDTO> documents) {
Not needed

2021-01-08 00:58 UTC, DanielFran commented on src/main/java/uc/dei/mse/supportivecare/web/rest/OutcomeResource.java
> +            outcomeDTO.addToDocuments(documentContentMapper.multiPartFilesToDocuments(files));
Substitute by outcomeDTO.getDocuments.addAll(documentContentMapper.multiPartFilesToDocuments(files));

2021-01-09 00:39 UTC, andrenns approved these changes

2021-01-09 01:07 UTC, merged